import dns from 'node:dns'
dns.setServers(['8.8.8.8','8.8.4.4'])


import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}    >
      <body>
        <Navbar />
        <main className=" min-h-screen">
          {children}
        </main>
        <Footer />

        <Toaster
          position="top-center"
          reverseOrder={false}
        />
      </body>
    </html>
  );
}
